#!/bin/bash

echo "Installing the following optional packages:"

pkgs="calibre gimp pdfarranger inkscape ttf-ms-fonts slack-desktop"

echo $pkgs

yay -S $pkgs --noconfirm

echo "Installation finished!"
