#!/bin/bash

echo "Installing the following programming packages:"
pkgs="visual-studio-code-bin cursor-bin bazel google-cloud-sdk"
echo $pkgs
yay -S $pkgs --noconfirm

mkdir -p ~/miniconda3
wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ~/miniconda3/miniconda.sh
bash ~/miniconda3/miniconda.sh -b -u -p ~/miniconda3
rm ~/miniconda3/miniconda.sh

~/miniconda3/bin/conda init bash
~/miniconda3/bin/conda init fish

conda tos accept --override-channels --channel https://repo.anaconda.com/pkgs/main       
conda tos accept --override-channels --channel https://repo.anaconda.com/pkgs/r

echo "Installation finished!"
